Disable no-console rule
vtex/eslint-config-vtex pull request #17
Opened 2019-02-15 20:16 UTC by lucasecdb

2019-02-15 20:27 UTC, thiagomurakami commented
Why do you want to change this rule? A bit of context would help!

2019-02-15 20:34 UTC, lucasecdb commented
@thiagomurakami I've updated the PR description accordingly.

2019-02-15 20:41 UTC, klzns approved these changes

2019-02-15 21:23 UTC, JuanAlmeida12 approved these changes

2019-02-15 23:47 UTC, jgfidelis commented
I am against this. `console` should be avoided for performance reasons. If you REALLY want an console in your code, you should do:
```
// eslint-disable-next-line
console.error('deu ruim!')
```

2019-02-15 23:51 UTC, lbebber commented
not even only for the sake of performance, but for cleanliness. it's very easy to forget stray `console.logs` and render the console a mess

2019-02-15 23:51 UTC, lbebber commented
at any rate, you could allow it exclusively for, say, `console.error`

https://eslint.org/docs/rules/no-console#options

2019-02-15 23:52 UTC, lbebber reviewed
(messed up and can't delete this)

2019-02-15 23:52 UTC, lbebber requested changes
☝️

2019-02-18 13:15 UTC, lbebber approved these changes
Just left a suggestion to update the changelog

2019-02-18 13:15 UTC, lbebber commented on CHANGELOG.md
> +- Disable `no-console` rule.
```suggestion
- Disable `no-console` rule for warnings and errors.
```

2019-02-18 13:29 UTC, jgfidelis approved these changes

2019-02-18 19:00 UTC, merged